# CHECK_HAVE(_GNU_SOURCE, string.h, memrchr)
# CHECK_STRUCT(net/in.h, struct in_addr, s_addr)
# CHECK_HAVE(linux/ipv6.h)
# CHECK_SIZEOF(int *)
# CHECK_HAVE(rexxsaa.h)
# CHECK_SIZEOF(sys/types.h, off_t)
# CHECK_HAVE(sys/mount.h)
# CHECK_HAVE(sys/param.h)
# CHECK_DECL(sys.mtio.h, MTEWARN)
# CHECK_SIZEOF(long)
# CHECK_SIZEOF(pthread.h, pthread_t)
# CHECK_HAVE(byteswap.h)
# CHECK_HAVE(linux/if/tun.h)
# CHECK_DECL(sys/socket.h, netinet/in.h, netinet/tcp.h, TCP_KEEPIDLE)
# CHECK_SIZEOF(stddef.h, size_t)
# CHECK_HAVE(sys/mtio.h)
# CHECK_HAVE(bzlib.h)
# CHECK_WORDS_BIGENDIAN
# CHECK_ENABLE(ipv6)
# CHECK_SIZEOF(int)
# CHECK_HAVE(sys/prctl.h)
# CHECK_DECL(sys/socket.h, netinet/in.h, netinet/tcp.h, TCP_KEEPCNT)
# CHECK_DECL(sys/socket.h, netinet/in.h, netinet/tcp.h, TCP_KEEPINTVL)
# CHECK_HAVE(zlib.h)
# CHECK_HAVE(sys/socket.h, netinet/in.h, arpa/inet.h, inet_aton)
# CHECK_HAVE(getopt.h, getopt_long)
